### ISSUE TITLE
opening a diff crashes rls

### ISSUE THREAD

**Issue by radix** [rust-lang-nursery/rls-vscode#93]
repro:

1. note that RLS generally works. at least go to definition and rustfmt.
2. change a file (I used alt+shift+f to format the document with rls/rustfmt)
3. click the changed file in the Source Control sidebar to view the diff
4. RLS crashes: "The Rust Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted."

here's a sample from the "Output" tab, "Rust Language Server" section:

```
[Error - 5:00:49 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (C:\Users\radix\.vscode\extensions\rust-lang.rust-0.1.0\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\main.js:816:25)
    at Object.dispose (C:\Users\radix\.vscode\extensions\rust-lang.rust-0.1.0\node_modules\vscode-languageclient\lib\client.js:66:35)
    at LanguageClient.handleConnectionClosed (C:\Users\radix\.vscode\extensions\rust-lang.rust-0.1.0\node_modules\vscode-languageclient\lib\client.js:1071:38)
    at LanguageClient.handleConnectionClosed (C:\Users\radix\.vscode\extensions\rust-lang.rust-0.1.0\node_modules\vscode-languageclient\lib\main.js:86:15)
    at closeHandler (C:\Users\radix\.vscode\extensions\rust-lang.rust-0.1.0\node_modules\vscode-languageclient\lib\client.js:1059:18)
    at CallbackList.invoke (C:\Users\radix\.vscode\extensions\rust-lang.rust-0.1.0\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\events.js:114:39)
    at Emitter.fire (C:\Users\radix\.vscode\extensions\rust-lang.rust-0.1.0\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\events.js:178:36)
    at closeHandler (C:\Users\radix\.vscode\extensions\rust-lang.rust-0.1.0\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\main.js:212:26)
    at CallbackList.invoke (C:\Users\radix\.vscode\extensions\rust-lang.rust-0.1.0\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\events.js:114:39)
    at Emitter.fire (C:\Users\radix\.vscode\extensions\rust-lang.rust-0.1.0\node_modules\vscode-languageclient\node_modules\vscode-jsonrpc\lib\events.js:178:36)
[Info  - 5:00:49 PM] Connection to server got closed. Server will restart.
```

**Comment by Xanewok** [comment]
This is tracked over at https://github.com/rust-lang-nursery/rls/issues/421.

**Comment by nrc** [comment]
And should be fixed now
